name: Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
        env:
          CI: false
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: github-pages
          folder: build

permissions:
  contents: write
